[2025-08-02 17:40:52,880] 97 werkzeug - WARNING -  * Debugger is active!
[2025-08-02 17:40:52,893] 97 werkzeug - INFO -  * Debugger PIN: 211-603-832
[2025-08-02 17:41:13,350] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:41:13] "GET / HTTP/1.1" 200 -
[2025-08-02 17:41:14,461] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:41:14] "GET / HTTP/1.1" 200 -
[2025-08-02 17:41:21,263] 21 root - INFO - >>> /train endpoint called
[2025-08-02 17:41:21,263] 69 root - INFO - Entered initiated_data_ingestion method of data_integration class
[2025-08-02 17:41:21,263] 46 root - INFO - Exporting data from mongodb
[2025-08-02 17:41:56,088] 32 root - ERROR - >>> Exception occurred in /train: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\pipeline\train_pipeline.py] at line [41]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\pipeline\train_pipeline.py] at line [15]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [72]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [51]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [31]: SSL handshake failed: ac-oec3urt-shard-00-01.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-oec3urt-shard-00-02.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-oec3urt-shard-00-00.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 688e00695607c0d747cb8393, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-oec3urt-shard-00-00.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-oec3urt-shard-00-00.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-oec3urt-shard-00-01.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-oec3urt-shard-00-01.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-oec3urt-shard-00-02.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-oec3urt-shard-00-02.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2025-08-02 17:41:56,388] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:41:56] "[35m[1mGET /train HTTP/1.1[0m" 500 -
[2025-08-02 17:41:56,721] 21 root - INFO - >>> /train endpoint called
[2025-08-02 17:41:56,722] 69 root - INFO - Entered initiated_data_ingestion method of data_integration class
[2025-08-02 17:41:56,722] 46 root - INFO - Exporting data from mongodb
[2025-08-02 17:42:31,095] 32 root - ERROR - >>> Exception occurred in /train: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\pipeline\train_pipeline.py] at line [41]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\pipeline\train_pipeline.py] at line [15]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [72]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [51]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [31]: SSL handshake failed: ac-oec3urt-shard-00-01.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-oec3urt-shard-00-02.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-oec3urt-shard-00-00.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 688e008c5607c0d747cb8394, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-oec3urt-shard-00-00.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-oec3urt-shard-00-00.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-oec3urt-shard-00-01.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-oec3urt-shard-00-01.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-oec3urt-shard-00-02.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-oec3urt-shard-00-02.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2025-08-02 17:42:31,096] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:42:31] "[35m[1mGET /train HTTP/1.1[0m" 500 -
[2025-08-02 17:47:09,572] 21 root - INFO - >>> /train endpoint called
[2025-08-02 17:47:09,572] 69 root - INFO - Entered initiated_data_ingestion method of data_integration class
[2025-08-02 17:47:09,572] 46 root - INFO - Exporting data from mongodb
[2025-08-02 17:47:43,854] 32 root - ERROR - >>> Exception occurred in /train: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\pipeline\train_pipeline.py] at line [41]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\pipeline\train_pipeline.py] at line [15]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [72]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [51]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [31]: SSL handshake failed: ac-oec3urt-shard-00-01.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-oec3urt-shard-00-02.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-oec3urt-shard-00-00.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 688e01c55607c0d747cb8395, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-oec3urt-shard-00-00.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-oec3urt-shard-00-00.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-oec3urt-shard-00-01.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-oec3urt-shard-00-01.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-oec3urt-shard-00-02.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-oec3urt-shard-00-02.noxunci.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2025-08-02 17:47:43,857] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:47:43] "[35m[1mGET /train HTTP/1.1[0m" 500 -
[2025-08-02 17:49:05,770] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:49:05] "GET / HTTP/1.1" 200 -
[2025-08-02 17:51:37,337] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:51:37] "GET /predict HTTP/1.1" 200 -
[2025-08-02 17:51:37,389] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:51:37] "[33mGET /styles.css HTTP/1.1[0m" 404 -
[2025-08-02 17:56:49,627] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:56:49] "GET /predict HTTP/1.1" 200 -
[2025-08-02 17:56:49,757] 97 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 17:56:49] "[33mGET /styles.css HTTP/1.1[0m" 404 -
