[2025-08-02 18:28:18,482] 224 werkzeug - WARNING -  * Debugger is active!
[2025-08-02 18:28:18,489] 224 werkzeug - INFO -  * Debugger PIN: 129-964-374
[2025-08-02 18:28:18,517] 21 root - INFO - >>> /train endpoint called
[2025-08-02 18:28:18,518] 69 root - INFO - Entered initiated_data_ingestion method of data_integration class
[2025-08-02 18:28:18,518] 46 root - INFO - Exporting data from mongodb
[2025-08-02 18:28:54,099] 32 root - ERROR - >>> Exception occurred in /train: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\pipeline\train_pipeline.py] at line [41]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\pipeline\train_pipeline.py] at line [15]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [72]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [51]: Error occurred in Python script [D:\DS_Himanshu_Files\DATA SCIENCE\Jupyter_Notebook\SENSOR PROJECT\src\components\data_ingestion.py] at line [31]: SSL handshake failed: ac-oec3urt-shard-00-02.noxunci.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-oec3urt-shard-00-00.noxunci.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-oec3urt-shard-00-01.noxunci.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 688e0b6a7c20ff41537a4ceb, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-oec3urt-shard-00-00.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect("SSL handshake failed: ac-oec3urt-shard-00-00.noxunci.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)")>, <ServerDescription ('ac-oec3urt-shard-00-01.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect("SSL handshake failed: ac-oec3urt-shard-00-01.noxunci.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)")>, <ServerDescription ('ac-oec3urt-shard-00-02.noxunci.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect("SSL handshake failed: ac-oec3urt-shard-00-02.noxunci.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)")>]>
[2025-08-02 18:28:54,403] 224 werkzeug - INFO - 127.0.0.1 - - [02/Aug/2025 18:28:54] "[35m[1mGET /train HTTP/1.1[0m" 500 -
[2025-08-02 18:30:56,299] 224 werkzeug - INFO -  * Detected change in 'C:\\Users\\haima\\anaconda3\\Scripts\\pip-script.py', reloading
[2025-08-02 18:30:56,723] 224 werkzeug - INFO -  * Detected change in 'C:\\Users\\haima\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\pyparsing\\core.py', reloading
[2025-08-02 18:30:56,798] 224 werkzeug - INFO -  * Detected change in 'C:\\Users\\haima\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\packaging\\markers.py', reloading
